/-
Copyright (c) 2025. All rights reserved.
Author: Julián Calderón Almendros
License: MIT
-/

-- Root module: auto-generated by gen-root.bash
-- Uses barrel imports for subdirectories (see AI-GUIDE.md §23, §30–33).
-- Run 'bash gen-root.bash' after adding or removing modules.

import Robinson.Prelim
